<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'http://dataweb.innovex.cl/api_register/token/');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=password&username=uss-boya&password=innovex2021");
curl_setopt($ch, CURLOPT_USERPWD, 'krsE4KVdxGU9rC6kGMn97ipHxV8ims0CBaGgbR2p' . ':' . 'RQuuZINi2pzi8Cznqtx2jhh8sQ2AuFLRRzyMNxKKoP69AZMPB1ymejQ4vXic8c9o1YS7KnnkKQ2vNuPqawcqnxumRVF8Tot0VaXr8NTcWwlY6qWHZxQ6RgTSAGJcycFG');

$headers = array();
$headers[] = 'Content-Type: application/x-www-form-urlencoded';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
print_r($result);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
?>