<?php
function generateFromScratch() {
	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, 'http://dataweb.innovex.cl/api_register/token/');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POST, 1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=password&username=uss-boya&password=innovex2021");
	curl_setopt($ch, CURLOPT_USERPWD, 'krsE4KVdxGU9rC6kGMn97ipHxV8ims0CBaGgbR2p' . ':' . 'RQuuZINi2pzi8Cznqtx2jhh8sQ2AuFLRRzyMNxKKoP69AZMPB1ymejQ4vXic8c9o1YS7KnnkKQ2vNuPqawcqnxumRVF8Tot0VaXr8NTcWwlY6qWHZxQ6RgTSAGJcycFG');

	$headers = array();
	$headers[] = 'Content-Type: application/x-www-form-urlencoded';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

	$result = curl_exec($ch);
	//print_r($result);
	
	if (curl_errno($ch)) {
		echo 'Error:' . curl_error($ch);
	} else {
		file_put_contents('../token.json', $result);
		$obj = json_decode($result); 
		
		$return_array = array();
		$return_array['access_token'] = $obj->access_token;
		$return_array['refresh_token'] = $obj->refresh_token;	
		return $return_array;
	}
	curl_close($ch);
}

function getActualToken() {
	$file = '../token.json'; 
	// put the content of the file in a variable
	$data = file_get_contents($file); 
	// JSON decode
	$obj = json_decode($data); 

	// display the name of the first person	
	$return_array = array();
	$return_array['access_token'] = $obj->access_token;
	$return_array['refresh_token'] = $obj->refresh_token;
	return $return_array;
}

function refreshToken($token) {
	$refresh_token = $token['refresh_token'];
	//$access_token = $token['access_token'];
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();
	
	curl_setopt($ch, CURLOPT_URL, 'http://dataweb.innovex.cl/api_register/token/');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POST, 1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=refresh_token&refresh_token=$refresh_token");
	curl_setopt($ch, CURLOPT_USERPWD, '4fGjovn7bQv7yiFNi6UN2TZtLFiGBrWUeaXZddag' . ':' . 'pMDYEGTPrax8SA38cN5pScaJ1iSuuNQpEH3e87t7Wc6XyuXLeZbNdJbcwXmDapORCRxIfM07hZ807MLBWHhFWS7KzjgaGT88fxqnGAjxemL1NpwempLlGu6vd2q2XN2K');

	$headers = array();
	$headers[] = 'Content-Type: application/x-www-form-urlencoded';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

	$result = curl_exec($ch);

	if (curl_errno($ch)) {
		echo 'Error:' . curl_error($ch);
	} else {
		if ($result->error <> '') {
			file_put_contents('../token.json', $result);
			$obj = json_decode($result); 
			curl_close($ch);
			
			$return_array = array();
			$return_array['access_token'] = $obj->access_token;
			$return_array['refresh_token'] = $obj->refresh_token;
			return $return_array;
		} else {
			$a = generateFromScratch();
			return $a;
		}
	}	
}
?>